version: 2
updates:
  # Enable version updates for npm (monthly for low-activity projects)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "@aguilerap-jc"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Ignore patch and minor updates, only allow security and major updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    
  # Enable version updates for GitHub Actions (monthly for low-activity projects)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday" 
      time: "09:00"
    open-pull-requests-limit: 1
    # Ignore patch and minor updates, only allow security and major updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
